### ISSUE TITLE
Design changes from Twitter

### ISSUE THREAD

**Issue by MetroidCatcher** [dubstrike/twitter-dark-mode#32]
The "Following" button is now white, with white text and green (Depends what color is set in the Twitter settings) borders. Applies also to the "Who to follow" list on the right, except this is a "Follow" button. (ALSO applies to logged out users) Also they changed the "Show more replies" in Tweets.
Pictures attached.
![firefox_2017-05-17_22-13-50](https://cloud.githubusercontent.com/assets/16920375/26174000/5c8dec7c-3b3d-11e7-94f1-7bb6a0cc6d52.jpg)
![firefox_2017-05-17_22-12-56](https://cloud.githubusercontent.com/assets/16920375/26174001/5c9022bc-3b3d-11e7-9cf2-ae16af1060dd.jpg)
![firefox_2017-05-17_22-12-42](https://cloud.githubusercontent.com/assets/16920375/26174002/5c93214c-3b3d-11e7-967b-9d46567ab010.jpg)

**Comment by Kn0p3XX** [comment]
Oh, and i found this weird looking "Following" button.
![firefox_2017-05-17_22-17-39](https://cloud.githubusercontent.com/assets/16920375/26174131/e55671b4-3b3d-11e7-93d6-5eb5e8c9a7ee.jpg)

**Comment by MetroidCatcher** [comment]
Oh, i found this kind of weird looking "Following" button (This is a different user's chosen color, thingy)
![firefox_2017-05-17_22-17-39](https://cloud.githubusercontent.com/assets/16920375/26174185/19af3b3a-3b3e-11e7-8d2b-e744d13a95ed.jpg)

**Comment by pugson** [comment]
Thanks for screenshotting this. The buttons have been fixed with https://github.com/dubstrike/twitter-dark-mode/commit/925ea8bae4f8803ee6acc13fbce7131e4478c272

Updating the other changes as we speak.

**Comment by pugson** [comment]
@Kn0p3XX Where did you see "Show more replies"? I cannot find it anywhere on my feed.

**Comment by MetroidCatcher** [comment]
The "Show more replies" isn't fixed (still).
Also, the "Following" and "Follow" buttons are half way fixed(?) But it's not a big deal. (Maybe that can't be fixed anymore, i guess?)
![firefox_2017-05-18_09-59-23](https://cloud.githubusercontent.com/assets/16920375/26192118/018d611e-3ba0-11e7-8338-1e070a7f6066.jpg)

**Comment by MetroidCatcher** [comment]
Also, if you clicked on "Show more replies" this is what i see.
![firefox_2017-05-19_12-49-53](https://cloud.githubusercontent.com/assets/16920375/26244790/e8ac3468-3c80-11e7-8eaf-fa8175faf686.jpg)

**Comment by pugson** [comment]
@Kn0p3XX Can you send me a link that has this "Show more replies" button? I can't fix it if I don't see it.

**Comment by MetroidCatcher** [comment]
For example you can see it here:
https://twitter.com/GamepIay/status/860569067903754240
(Scroll all the way down and there's it)

**Comment by pugson** [comment]
Hmm, not appearing for me.
![img](http://share.wojtek.im/J9GYF+)

**Comment by MetroidCatcher** [comment]
That's weird.. i see it. Btw, "Weitere Antworten anzeigen" means "Show more replies".
![firefox_2017-05-19_23-19-38](https://cloud.githubusercontent.com/assets/16920375/26267297/e6089c08-3cd8-11e7-831d-9eb447faee11.jpg)
![firefox_2017-05-19_23-19-55](https://cloud.githubusercontent.com/assets/16920375/26267305/ea8c93d8-3cd8-11e7-8567-876687f0ab1e.jpg)

**Comment by pugson** [comment]
Must be some A/B test then. Let me try using a German VPN.

**Comment by MetroidCatcher** [comment]
Even for logged out users and for different users will be displayed differently. (I have multiple accounts, and on my other one, it's not there.. why.) Twitter is weird. :|

**Comment by pugson** [comment]
Yeah, must be account-based. I can't get it to display in any way 😞 Only way for me to fix this at the moment is if you shared the class names that are adding the white background color to these elements.

**Comment by MetroidCatcher** [comment]
Hmm.. i hope i did the right thing.
So far what i see is this.
Thats the "Show more replies" button.
`    <li class="ThreadedConversation-showMoreThreads" data-element-context="show_more_threads_button"
    data-cursor-type-name="ShowMoreThreads">
        <button class="ThreadedConversation-showMoreThreadsButton u-textUserColor" data-cursor="DAACDwABCgAAAAcL8YXV3FeQAAvxX48MVtAAC_Fh4A_WsAAL8V2aQVWgAAvxW2wrl6ACC_FbSZQXgAEL8V-4ZhXAAAgAAwAAAAICAAQBAAA">Weitere Antworten anzeigen</button>
      <span class="ThreadedConversation-showMoreSpinner u-hidden"></span>
    </li>`
Second is the "More replies"
` <div class="ThreadedConversation--header">
      More replies
    </div><div class="ThreadedConversation--loneTweet">`
Hopefully i found the right classes... apologies, i don't know much about classes, HTML in general. :|

**Comment by pugson** [comment]
Go ahead and update the style to the latest version. Let me know if that fixed it @Kn0p3XX

**Comment by MetroidCatcher** [comment]
Yep, it's fixed. Thank you.
![firefox_2017-05-19_23-42-47](https://cloud.githubusercontent.com/assets/16920375/26267913/100b4b10-3cdc-11e7-950d-f226160c94b9.jpg)
![firefox_2017-05-19_23-42-41](https://cloud.githubusercontent.com/assets/16920375/26267912/0fe49ace-3cdc-11e7-9013-855e86ffa7dd.jpg)

**Comment by pugson** [comment]
Great, thanks for your help!

**Comment by MetroidCatcher** [comment]
You're welcome. :)
