### ISSUE TITLE
Change Trends Selected Location still Light Themed

### ISSUE THREAD

**Issue by EthanC** [dubstrike/twitter-dark-mode#56]
![image](https://user-images.githubusercontent.com/16727756/27519045-f8003722-59b1-11e7-9df1-8b96640d605c.png)

**Comment by pugson** [comment]
Fixed here https://github.com/dubstrike/twitter-dark-mode/commit/73f3e9fbe3be7bf9aca8ffbdfce12eef75e43a6c#diff-a48f9b1843498ef73e98afc8378587aeR620

**Comment by EthanC** [comment]
On the latest Update, Chrome/Windows, not fixed
![image](https://user-images.githubusercontent.com/16727756/27615116-9dd99728-5b6b-11e7-95e7-bb94c92de8d5.png)

**Comment by EthanC** [comment]
![image](https://user-images.githubusercontent.com/16727756/27952700-d0a4d0e0-62ce-11e7-957e-77f8b0fbdaba.png)
Very latest update, caches cleared, still having the issue.
